CREATE TABLE users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    user_type TEXT,
    first_name TEXT,
    last_name TEXT,
    location TEXT,
    profile_photo TEXT,
    telephone_number TEXT,
    bio TEXT,
    birthday DATE,
    title TEXT,
    skills JSONB DEFAULT '[]',
    department TEXT,
    company_name TEXT,
    employee_id TEXT,
    start_date DATE,
    level TEXT,
    education JSONB DEFAULT '[]',
    experience JSONB DEFAULT '[]',
    profile_headline TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);